### ISSUE TITLE
Possible missing file history

### ISSUE THREAD

**Issue by fabiodr** [yinghaochan/redux-meteor#2]
I got the bellow error, it seems a history file is missing.

ERROR in ./entry/client/root.jsx
Module not found: Error: Cannot resolve module 'history' in C:\MeteorLab\redux-meteor\entry\client
 @ ./entry/client/root.jsx 13:15-33

**Comment by yinghaochan** [comment]
@fabiodr Thanks! A few people who tried it out also mentioned the same, though it oddly works on my machine.
